// <auto-generated />
using System;
using Blog.Models.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230904141123_initdb")]
    partial class initdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blog.Models.Entities.Konu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KonuAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Konus");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7099),
                            IsActive = true,
                            KonuAdi = "Teknoloji",
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7112)
                        },
                        new
                        {
                            ID = 2,
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7155),
                            IsActive = true,
                            KonuAdi = "Felsefe",
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7155)
                        },
                        new
                        {
                            ID = 3,
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7156),
                            IsActive = true,
                            KonuAdi = "Bilim",
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7157)
                        },
                        new
                        {
                            ID = 4,
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7157),
                            IsActive = true,
                            KonuAdi = "Yazılım",
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7158)
                        },
                        new
                        {
                            ID = 5,
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7159),
                            IsActive = true,
                            KonuAdi = "Kişisel Gelişim",
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7159)
                        },
                        new
                        {
                            ID = 6,
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7160),
                            IsActive = true,
                            KonuAdi = "Film",
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7160)
                        });
                });

            modelBuilder.Entity("Blog.Models.Entities.Makale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KonuID")
                        .HasColumnType("int");

                    b.Property<string>("MakaleImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OkunmaSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("OkunmaSuresi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YazarID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KonuID");

                    b.HasIndex("UserId");

                    b.ToTable("Makales");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Baslik = "1.Makale Başlığı",
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7274),
                            Icerik = "1. Makale İçeriği",
                            IsActive = true,
                            KonuID = 1,
                            OkunmaSayisi = 0,
                            OkunmaSuresi = 0,
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7275),
                            YazarID = 0
                        },
                        new
                        {
                            ID = 2,
                            Baslik = "2.Makale Başlığı",
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7277),
                            Icerik = "2. Makale İçeriği",
                            IsActive = true,
                            KonuID = 2,
                            OkunmaSayisi = 0,
                            OkunmaSuresi = 0,
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7277),
                            YazarID = 0
                        },
                        new
                        {
                            ID = 3,
                            Baslik = "3.Makale Başlığı",
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7278),
                            Icerik = "3. Makale İçeriği",
                            IsActive = true,
                            KonuID = 3,
                            OkunmaSayisi = 0,
                            OkunmaSuresi = 0,
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7279),
                            YazarID = 0
                        },
                        new
                        {
                            ID = 4,
                            Baslik = "4.Makale Başlığı",
                            CreateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7280),
                            Icerik = "4. Makale İçeriği",
                            IsActive = true,
                            KonuID = 4,
                            OkunmaSayisi = 0,
                            OkunmaSuresi = 0,
                            UpdateDate = new DateTime(2023, 9, 4, 17, 11, 23, 266, DateTimeKind.Local).AddTicks(7280),
                            YazarID = 0
                        });
                });

            modelBuilder.Entity("Blog.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "eb3f3ad4-d8fd-4215-952d-7c072cd37292",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "547ed837-674c-4087-94a3-1392ff92a576",
                            Name = "Standard",
                            NormalizedName = "STANDARD"
                        });
                });

            modelBuilder.Entity("Blog.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("binary");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Blog.Models.Entities.UserMakale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MakaleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MakaleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserMakales");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Blog.Models.Entities.Makale", b =>
                {
                    b.HasOne("Blog.Models.Entities.Konu", "Konu")
                        .WithMany("Makale")
                        .HasForeignKey("KonuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Models.Entities.User", "User")
                        .WithMany("Makales")
                        .HasForeignKey("UserId");

                    b.Navigation("Konu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Models.Entities.UserMakale", b =>
                {
                    b.HasOne("Blog.Models.Entities.Makale", "Makale")
                        .WithMany("UserMakales")
                        .HasForeignKey("MakaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Models.Entities.User", "User")
                        .WithMany("UserMakales")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makale");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Blog.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Blog.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Blog.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Blog.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Blog.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blog.Models.Entities.Konu", b =>
                {
                    b.Navigation("Makale");
                });

            modelBuilder.Entity("Blog.Models.Entities.Makale", b =>
                {
                    b.Navigation("UserMakales");
                });

            modelBuilder.Entity("Blog.Models.Entities.User", b =>
                {
                    b.Navigation("Makales");

                    b.Navigation("UserMakales");
                });
#pragma warning restore 612, 618
        }
    }
}
